FAT_lib: D:/prog/itk_fat/interface.h File Reference
D:/prog/itk_fat/interface.h File Reference
All of the abstract functions used by FAT library.
Variables
s8(* fs_fat_read_sector_to_buffer)(u32, void *)
s8(* fs_fat_write_sector_from_buffer)(u32, void *)
void *(* fs_fat_memcpy)(void *destination, const void *source, u32 num)
Detailed Description
All of the abstract functions used by FAT library.
These few, simple functions should be implemented properly in order to make the FAT library work correctly. No other user-implemented nor standard C library functions are needed for working.
Definition in file interface.h.
Variable Documentation
void*(* fs_fat_memcpy)(void *destination, const void *source, u32 num)
Pointer to a function that copies num bytes of memory from source to destination.
Parameters:
destination Destination memory address.
source Source memory address.
num Number of bytes to copy.
Referenced by fs_fat_fopen(), fs_fat_fread(), fs_fat_fresize(), and fs_fat_fwrite().
s8(* fs_fat_read_sector_to_buffer)(u32, void *)
Pointer to a function that reads one sector from storage device to a given memory address.
Parameters:
lba LBA address of sector to read.
address Memory address to write to.
Returns:
Zero if error.
s8(* fs_fat_write_sector_from_buffer)(u32, void *)
Pointer to a function that writes one sector to storage device from a given memory address.
Parameters:
lba LBA address of sector to write.
address Memory address to read from.
Returns:
Zero if error.